version: '3.3'

services:
    mongo:
     image: mongo:latest
     container_name: mongo
     tty: true
     ports:
      - 27017:27017
     environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: cibc
     volumes:
      - ./mongodb:/data/db #this will mount mongodb to /data/db directory of docker container
